# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import telemetry_pb2 as telemetry__pb2


class TelemetryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveTemperature = channel.unary_unary(
                '/Telemetry/SaveTemperature',
                request_serializer=telemetry__pb2.Temperature.SerializeToString,
                response_deserializer=telemetry__pb2.Reply.FromString,
                )
        self.SaveHumidity = channel.unary_unary(
                '/Telemetry/SaveHumidity',
                request_serializer=telemetry__pb2.Humidity.SerializeToString,
                response_deserializer=telemetry__pb2.Reply.FromString,
                )
        self.SaveWeather = channel.unary_unary(
                '/Telemetry/SaveWeather',
                request_serializer=telemetry__pb2.Weather.SerializeToString,
                response_deserializer=telemetry__pb2.Reply.FromString,
                )


class TelemetryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveHumidity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveWeather(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveTemperature,
                    request_deserializer=telemetry__pb2.Temperature.FromString,
                    response_serializer=telemetry__pb2.Reply.SerializeToString,
            ),
            'SaveHumidity': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveHumidity,
                    request_deserializer=telemetry__pb2.Humidity.FromString,
                    response_serializer=telemetry__pb2.Reply.SerializeToString,
            ),
            'SaveWeather': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveWeather,
                    request_deserializer=telemetry__pb2.Weather.FromString,
                    response_serializer=telemetry__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Telemetry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Telemetry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Telemetry/SaveTemperature',
            telemetry__pb2.Temperature.SerializeToString,
            telemetry__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveHumidity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Telemetry/SaveHumidity',
            telemetry__pb2.Humidity.SerializeToString,
            telemetry__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveWeather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Telemetry/SaveWeather',
            telemetry__pb2.Weather.SerializeToString,
            telemetry__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
